name: wissler
description: The Wissler Matching Application.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_core:
    path: ../../packages/shared_core
  shared_ui:
    path: ../../packages/shared_ui
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
