name: wissler
description: The Wissler Matching Application.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_core:
    path: ../../packages/shared_core
  shared_ui:
    path: ../../packages/shared_ui
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1
  image_picker: ^1.2.1
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  appinio_swiper: ^2.0.5
  local_auth: ^2.1.8
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#FFFFFF"
