name: shared_core
description: Core logic and services for FitIt and Wissler.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_riverpod: ^2.4.9
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  api_client:
    path: ../api_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
