name: shared_ui
description: Reusable UI components for FitIt and Wissler.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1
  shared_core:
    path: ../shared_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
